version: 0.0
os: linux
runas: ubuntu
files:
  - source: /
    destination: /app/esgapi
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu
    
hooks:
  
  # Execute BeforeInstall only for the first time if node is not configured in system 
  #BeforeInstall:
    #- location: scripts/nodeconfigure.sh
  Install:
    - location: scripts/webconfigure.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
    - location: scripts/appbuild.sh
      timeout: 600
      runas: ubuntu
  ApplicationStop:
    - location: scripts/webstop.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: scripts/webstartservice.sh
      timeout: 600
      runas: ubuntu
  ValidateService:
    - location: scripts/monitorservice.sh
      timeout: 600
      runas: ubuntu
